### ISSUE TITLE
Message type "caffe.LayerParameter" has no field named "smooth_l1_loss_param".

### ISSUE THREAD

**Issue by lianlengyunyu** [mahyarnajibi/SSH#1]
Hello, I down the VGG16.caffemodel with the download_imgnet_model.sh,when I run the main_train.py, it comes with the error：
 Error parsing text-format caffe.NetParameter: 849:24: Message type "caffe.LayerParameter" has no field named "smooth_l1_loss_param".
How can I deal with it，Thanks very much for your nice code and your help

**Comment by po0ya** [comment]
You should make sure that you are compiling the provided caffe and putting the python directory of the compiled caffe in your PYTHONPATH environment variable.

**Comment by lianlengyunyu** [comment]
Yes, I have complied the caffe-ssh which you provided, do as the caffe-windows operations as follows:
git checkout windows 
built_win.cmd

**Comment by lianlengyunyu** [comment]
Thanks very much, i merge the master branch to the windows branch,and solver it.
