### ISSUE TITLE
GPU configuration for SSH

### ISSUE THREAD

**Issue by bockholt** [mahyarnajibi/SSH#18]
Hi Guys,

I was wondering what GPU gpu card did you used in your experiments? I am using a GTX 970M. Even tried several configurations (/SSH/Configs) but none of them worked and I still finding out of memory error from cuda. I am using cuda 8.0 and cudnn 6.0.

#################### Configuration ####################
USE_GPU_NMS:  True
DATA_DIR:  /home/bockholt/probes/ssh-faceDetector/data
GPU_ID:  0
EPS:  1e-14
DEBUG:  False
MATLAB:  matlab
TEST{
    NMS_THRESH:  0.3
    SCALES:  [1200]
    ANCHOR_MIN_SIZE:  0
    N_DETS_PER_MODULE:  1000
    PYRAMID_BASE_SIZE:  [800, 1200]
    ORIG_SIZE:  False
    MAX_SIZE:  1600
}
ROOT_DIR:  /home/bockholt/probes/ssh-faceDetector
EXP_DIR:  ssh
PIXEL_MEANS:  [[[102.9801 115.9465 122.7717]]]
RNG_SEED:  3
#######################################################
Loading the network...Done!
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0119 16:57:22.624498  4045 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by bockholt** [comment]
I've just downloaded the paper and saw that in section 4:

"All models are trained on 4 GPUs in parallel using stochastic gradient descent. We use a mini-batch of 
images."

Is there any chance the code can run in the GTX970M?

**Comment by luoyetx** [comment]
your gpu memory is too small, try to down size the scales. i.e. `SACLES: [600], MAX_SIZE: 800`

**Comment by bockholt** [comment]
@luoyetx  Made it! Thanks for the tip.

**Comment by xinyaoguo** [comment]
@luoyetx I have a question whether the results of running on a GPU can reach the result provided by the author's paper?

**Comment by yanqian123** [comment]
@xinyaoguo hi . do you reach the result with one gpu??
i am doing it.......but it is bad

**Comment by bockholt** [comment]
@yanqian123 yes, after adjusting the scales and batch size. Ran smoothly, it takes roughly 1 second per image. But the results are impressive.
