### ISSUE TITLE
Link to download pretained model is broken

### ISSUE THREAD

**Issue by hsienkaikuo** [mahyarnajibi/SSH#19]
Seems that the download link is broken. Anyone have a copy to share?

**Comment by zhonhel** [comment]
I have the same problem, every time I download a 379 bytes file.

**Comment by zhonhel** [comment]
@hsienkaikuo hi, have you solved this problem ?

**Comment by mahyarnajibi** [comment]
The download links should be fixed now. Feel free to re-open the issue if you still can't download the models.

**Comment by zhonhel** [comment]
@mahyarnajibi 
Thank you very much~, It seems work fine.

**Comment by hsienkaikuo** [comment]
It works. Thanks
