### ISSUE TITLE
The model released seems go wrong;

### ISSUE THREAD

**Issue by jianyin2016** [mahyarnajibi/SSH#20]
Using the .sh file to get the model,end up with a error and a less than 30M caffe.model that can't be parsed,bellow is the info.
./data/SSH_models.tar.gz                     100%[+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++=>]  70.08M  56.1KB/s    in 38s     

2018-03-20 21:13:17 (25.3 KB/s) - ‘./data/SSH_models.tar.gz’ saved [73481470/73481470]

Done!
Unzipping the file...
SSH_models/
SSH_models/SSH.caffemodel

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Cleaning up...
All done!

Also I try to manually downloaded the .tar.gz file ,no way to unzip it ,both Windows and  linux failed;

**Comment by foralliance** [comment]
@jianyin2016 
have u solved the problem??
