### ISSUE TITLE
How to config training on one GPU

### ISSUE THREAD

**Issue by liuwuliuyun** [mahyarnajibi/SSH#23]
Hi,
I have encounter several questions when training on one gpu.
1. Where to change learning rate? I cant find learning rate para in config files.
2. I keep encounter this error:
Traceback (most recent call last):
  File "main_train.py", line 63, in <module>
    max_iter=args.iters, gpus=gpus)
  File "/SSH/SSH/train.py", line 167, in train_net
    uid = caffe.NCCL.new_uid()
AttributeError: type object 'NCCL' has no attribute 'new_uid'
Thanks

**Comment by liuwuliuyun** [comment]
Solve 2 on my own, this error is due to I haven't install nccl. The code in train.py says we have to use nccl even if we only use one gpu card.

**Comment by liuwuliuyun** [comment]
About 1, you cant change learning rate from config files.

**Comment by liuwuliuyun** [comment]
You need to change from solver_ssh.prototxt

**Comment by stonell007** [comment]
> Solve 2 on my own, this error is due to I haven't install nccl. The code in train.py says we have to use nccl even if we only use one gpu card.

Can you share your solution? For the second question, I installed NCLL, but still reported this error AttributeError: type object 'NCCL' has no attribute 'new_uid'.

**Comment by siriusdemon** [comment]
> > Solve 2 on my own, this error is due to I haven't install nccl. The code in train.py says we have to use nccl even if we only use one gpu card.
> 
> Can you share your solution? For the second question, I installed NCLL, but still reported this error AttributeError: type object 'NCCL' has no attribute 'new_uid'.

Recompile caffe and pycaffe
```
make clean
make all 
make pycaffe
```
