### ISSUE TITLE
download pretrain model error

### ISSUE THREAD

**Issue by billhyde** [mahyarnajibi/SSH#29]
when I run "download_ssh_model.sh",it return 
Length: 73481470 (70M), 530494 (518K) remaining [application/gzip]
Saving to: ‘./data/SSH_models.tar.gz’

./data/SSH_models.tar.gz                100%[++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++>]  70.08M  28.0KB/s    in 23s     

2018-06-08 08:04:51 (22.8 KB/s) - ‘./data/SSH_models.tar.gz’ saved [73481470/73481470]

Done!
Unzipping the file...
SSH_models/
SSH_models/SSH.caffemodel

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Cleaning up...
All done!

the model cannot be extraced, could you  please help me? or upload the model to another Network disk?
Thank you

**Comment by billhyde** [comment]
![qq 20180608231126](https://user-images.githubusercontent.com/17793530/41165881-568136da-6b71-11e8-87c4-4837b07426d7.png)

**Comment by billhyde** [comment]
![22222222](https://user-images.githubusercontent.com/17793530/41165928-81df6f0e-6b71-11e8-9aea-f59a1a166389.png)

**Comment by mahyarnajibi** [comment]
Hi,
I cannot reproduce the problem. However, I uploaded a zip version here:
http://legacydirs.umiacs.umd.edu/~najibi/download.php?name=ssh_zip

You can download and unzip it in the data folder manually. Hopefully this one works for you. Let me know if it does not.

**Comment by billhyde** [comment]
hi,sorry for reply late. The model you upload now works fine, thank you. By the way,the project is really a great work.

**Comment by mahyarnajibi** [comment]
Happy it worked!
