### ISSUE TITLE
type object 'NCCL' has no attribute 'new_uid'

### ISSUE THREAD

**Issue by Laviyy** [mahyarnajibi/SSH#33]
when i run python main_train.py --gpus 0,1,2,3. I have the problem 
`Traceback (most recent call last):
  File "main_train.py", line 63, in <module>
    max_iter=args.iters, gpus=gpus)
  File "/home/lavi/deepcode/face/SSH/SSH/train.py", line 167, in train_net
    uid = caffe.NCCL.new_uid()
AttributeError: type object 'NCCL' has no attribute 'new_uid'
`
How to solve it? Please help me.

**Comment by mahyarnajibi** [comment]
Hi @Laviyy,
I couldn't reproduce the error. Did you install the ```NCCL``` from the README link? Also what is the python version you are using? If you are using python 3, that might be the problem. Can you try python 2.7 in that case?

**Comment by Laviyy** [comment]
@mahyarnajibi Thank you i have solved it.
