### ISSUE TITLE
how can I run the demo on cpu?

### ISSUE THREAD

**Issue by junedgar** [mahyarnajibi/SSH#36]
Thank you for your great work.
I compiled the caffe-ssh only on cpu successfully, but when i ran `import caffe`, encountered error:Segmentation fault: 11.
systerm: macos
Can you give me some advices?

**Comment by exnx** [comment]
were you able to get run the demo on a cpu?

**Comment by junedgar** [comment]
@exnx  I ran the demo on Mac, but very slowly.

**Comment by junedgar** [comment]
@exnx  there is just change   https://github.com/mahyarnajibi/SSH/blob/3aeb296f861b0bc427535e81b4e16a97e77c0855/demo.py#L44 to use `caffe.set_mode_cpu()`. But you must compile the [ssh-caffe](https://github.com/mahyarnajibi/caffe-ssh/tree/38d3be3c1710b145faac98f4de8b60c5c4abfd67) without CUDA. Because the  caffe version is too old, after you compiled the caffe on mac, you may encounter problem `segmentation fault :11` when you import caffe.  You can find the solution in [#591](https://github.com/BVLC/caffe/issues/591).

**Comment by exnx** [comment]
@junedgar Thanks for the response!  Sorry to keep bugging you, but do you have any tips on how to compile the ssh-caffe without CUDA?  I'm kind of new to CS and not sure how to do this.  Any resources would be great!  Thanks!

Eric
