### ISSUE TITLE
what's the conv5_128_crop for?

### ISSUE THREAD

**Issue by julysix** [mahyarnajibi/SSH#5]
hi Mahyar,
  I've tried to achieve your paper before you release your code, but i didn't get the accuracy as you got. Mabye some details made my accuracy fall， I'm trying to figure it out. I see there is a 'con5_128_crop' layer in your net. What's work it does? How about if I remove it? 

best regards!

**Comment by mahyarnajibi** [comment]
Hi,
The crop layer is there just to make sure that the feature maps have the same spatial dimensions before the feature fusion.

**Comment by xinyaoguo** [comment]
@julysix Will your result finally reach the result of the thesis?Which changed?
