### ISSUE TITLE
How much GPU will be needed to run the demo.py? 

### ISSUE THREAD

**Issue by yanzi6969** [mahyarnajibi/SSH#7]
to detect the demo.jpg ,how much GPU needed?

**Comment by mahyarnajibi** [comment]
One GPU with 6G RAM should be sufficient. But you may also try reducing the SCALES and MAX_SIZE parameters in the config files if you are facing memory issues.

**Comment by yanzi6969** [comment]
@mahyarnajibi thanks for your reply.
I have tried on two severs with gpu,but all got the same error.Is it really because the RAM is not enough or some other problems ? 

zcy@k80:~/SSH-master$ python demo.py
#################### Configuration ####################
USE_GPU_NMS:  True
DATA_DIR:  /media/disk4t/zcy/SSH-master/data
GPU_ID:  0
EPS:  1e-14
DEBUG:  False
MATLAB:  matlab
TEST{
    NMS_THRESH:  0.3
    SCALES:  [500, 800, 1200, 1600]
    ANCHOR_MIN_SIZE:  0
    N_DETS_PER_MODULE:  1000
    PYRAMID_BASE_SIZE:  [800, 1200]
    ORIG_SIZE:  False
    MAX_SIZE:  -1
}
ROOT_DIR:  /media/disk4t/zcy/SSH-master
EXP_DIR:  ssh_pyramid
PIXEL_MEANS:  [[[ 102.9801  115.9465  122.7717]]]
RNG_SEED:  3
#######################################################
Loading the network...Done!
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1109 10:04:06.904853 22441 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted (core dumped)

Looking forward to your reply

**Comment by yewuyue111** [comment]
@yanzi6969 You should change the scales to [500, 800, 1200], without 1600,then you can run this demo.And you can find this in SSH/configs/wider_pyramid.yml.

**Comment by mahyarnajibi** [comment]
@yewuyue111 To increase the number of anchors you may change ANCHORS_PER_BATCH parameter. BATCH_SIZE is there from a previous version of the code. Thanks for bringing this up.
