### ISSUE TITLE
FDDB dataset precision problem， got a lower precision

### ISSUE THREAD

**Issue by whcjb** [mahyarnajibi/SSH#8]
Hi， I use your released model make a evaluation on the FDDB datasets, I got a Disc curve precision 90 at False Positive 400. I dont know why.
![sshdiscroc](https://user-images.githubusercontent.com/11767995/32420949-b8b6306e-c2cd-11e7-9bbc-38c3bfc0a095.png)

**Comment by mahyarnajibi** [comment]
Hi,
Are you using the same config mentioned in the paper? SCALES: [400,] and MAX_SIZE: 800.

**Comment by whcjb** [comment]
Hi, I use the config SCALES: [1200,], MAX_SIZE:1600. As you said, I should use the 400, 800, But is it would give a better result with the larger scales [1200, ] and 1600?

**Comment by mahyarnajibi** [comment]
Not necessarily as the FDDB images have lower resolution compared to the WIDER images.

**Comment by whcjb** [comment]
Great! When setting the SCALES to [400, ], MAX_SIZE to 800, got the surprising results.
![fddb_output_ypfdiscroc](https://user-images.githubusercontent.com/11767995/32470946-ce5344ca-c395-11e7-9b97-ed551eb84570.png)
